# Generated by Django 4.0.4 on 2022-06-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.IntegerField()),
                ('long', models.DecimalField(decimal_places=5, max_digits=7)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider')),
            ],
        ),
    ]
