# Generated by Django 4.0.5 on 2022-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='long',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
